### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by Kris1432** [bdew-minecraft/gendustry#20] opened 2014-05-05 11:18 UTC
http://pastebin.com/BjmV8MbY

**Comment by bdew** [comment] 2014-05-05 12:36
It looks like Forge fails to strip an IC2 interface from one of my classes when IC2 isn't present, but i can't reproduce that.

Can you post a full log (fml-client-latest.log) please?

Also where did forestry 2.4.1.16 come from? I don't see that version anywhere.

**Comment by Kris1432** [comment] 2014-05-05 12:51
i will do in a couple of hours when i'm at my computer, the build is on the IC2 Jenkins site

**Comment by bdew** [comment] 2014-05-05 12:55
Ok i see the problem now, no need for the log.
Will fix ASAP, for now you can install IC2 to work around it i think.

**Comment by bdew** [comment] 2014-05-05 15:06
Please try with this version, it should fix that crash

http://jenkins.bdew.net/job/gendustry-172/lastSuccessfulBuild/artifact/build/libs/gendustry-mc172-1.2.0.9.jar

**Comment by bdew** [comment] 2014-05-07 06:18
Can you confirm if it's really fixed or not? If i don't hear anything back i'll assume it is and close this issue.

**Closed as completed** 2014-05-12 23:25 UTC
