### ISSUE TITLE
EU bug

### ISSUE THREAD

**Issue by AiwendilCiunio** [bdew-minecraft/gendustry#137] opened 2015-09-28 08:51 UTC
I placed 4 Industrial Apiaries, each powered by its own MFE. They were working for a few days and then one by one, over a few days, they stopped receiving power. Even though MFE was full and was outputting towards the apiary. First only 1 apiary didn't accept power, but eventually (yesterday) all of them stopped working.

What I tried:
-breaking and replacing the apiary
-breaking and replacing the MFE
-breaking the apiary, putting some other block in its place, and the placing the apiary again.

None of above worked. When I placed the faulty apiaries somewhere else they accepted power fine.

Now comes the really weird part: I tried placing another chargeable block in apiaries' place, an MFE. And to my amazement it didn't charge up, even though it was next to a full MFE.

I broke all apiaries and waited till server restart, then replaced them. They are working (for now).

I'm not sure what's going on, but the bug has to do with coords, not specific blocks.

Also, before I used MFE to power my apiaries I tried using GregTech cables. They would fry randomly when I tried to connect them :/

Using Gendustry 1.6.0.125 and Infitech2 modpack.

**Comment by bdew** [comment] 2015-09-28 11:10
Sounds like an energy net bug. Were there any odd messages in the server log?

**Comment by AiwendilCiunio** [comment] 2015-09-29 22:48
Any particular words or phrases you're looking for?

**Comment by bdew** [comment] 2015-10-01 07:15
Not really. Any kind of error or warning mentioning the energy net.

IC2 exp has a lot of weird hard to diagnose bug in it's energy net code that's been undergoing a rewrite for over a year now... If you put a different block in it's place and it didn't receive power either it probably means that something was broken in IC2 internal data structures. 

It might be something in my code triggering that bug (in which case anything from the log might help pinpoint what), or it might be just general IC2 bugginess.

Added: Come to think of it - look for "Tile entity for block ____ at (__,__,__) is corrupt or missing - recreating". It could be that something else caused the apiaries to create "ghost" tile entities which then joined the energy net and weren't removed when the real block was broken.

Other keywords to look for: "EnergyNet.addTileEntity"  and  "using the same position (overlapping), aborting"

**Comment by AiwendilCiunio** [comment] 2015-10-02 18:09
Ok here's a bit of log:
http://pastebin.com/Wzd3AyzF

As you can see there are 2 EnergyNet warnings, which probably appeared when I tried to place an Industrial Apiary at the offending location.

**Comment by AiwendilCiunio** [comment] 2015-10-13 11:41
Any idea?

**Comment by bdew** [comment] 2015-10-14 07:27
Sorry for the long wait, i'm a bit busy IRL right now.

From the messages it looks like the apiary was not correctly removed from the energy net. The log shows only the lines when you tried to place an MFE at the same spot, there might have been other warnings leading up to this.

I did some basic testing and couldn't reproduce the issue. I'll need to go through the energy net (un)registration code to see maybe i can do something more to prevent issues like that, i'll try to do this ASAP.

**Comment by JasonMcRay** [comment] 2015-11-12 07:23
Hi @bdew Just would like to ask if you found out what can be causing this issue, or at least figured on how to make a "workaround" for this to prevent it from happening.

**Comment by bdew** [comment] 2015-11-14 16:12
Nope, i hadn't any luck in reproducing this or figuring out how exactly it goes wrong.

I haven't given up however, and will look more into this when i'm less overloaded with other stuff and RL issues.

**Comment by bdew** [comment] 2017-10-12 16:43
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:43 UTC
