### ISSUE TITLE
Custom Bee Species / Honeycomb Localizations no longer display

### ISSUE THREAD

**Issue by SargeRyong** [bdew-minecraft/gendustry#132] opened 2015-09-02 08:39 UTC
This worked in a previous version, but using these localizations no longer causes the correct names or descriptions to appear in-game.

Localization file:
![Localization File](http://i.imgur.com/4KoCLrt.png)

In-game strings not localized.
![In-game strings not localized](http://i.imgur.com/hMzSZHO.png)

Unlocalized honeycomb name
![ Unlocalized honeycomb name](http://i.imgur.com/kAFPx3T.png)
http://i.imgur.com/kAFPx3T.png

http://imgur.com/a/Xi5Lq

**Comment by bdew** [comment] 2015-09-02 14:58
What version? I can't reproduce it in the latest versions of neither the main branch nor -fu.

Are you sure the localisation data is where it's supposed to be?

**Comment by bdew** [comment] 2015-09-02 15:01
Also check your log, you should see something like:

```
[17:55:15] [Client thread/INFO]: Resource manager reload, new language: en_US
[17:55:15] [Client thread/INFO]: Loading language file <something>/config/gendustry/<something>.en_US.lang
```

**Comment by SargeRyong** [comment] 2015-09-02 15:25
I'm on 1.5.2-1.0.7 and the localization file is in the same dir as the .cfg that adds the bees - <instance folder>/config/Gendustry/custombees.en_US.lang.

In retrospect, I'm now realizing that 1.5.2-1.0.7 is the latest release version and that the latest alpha may have fixed this problem. Sorry, curse was serving me an older version than I thought it was - probably due to a "prefer release version" setting.  

I'll grab the latest alpha (1.6.0-1.2.2?) and try to reproduce and get back to you with the results.

(As an aside, are the alpha releases pretty stable?)

**Comment by bdew** [comment] 2015-09-02 16:42
Yep the alphas should be pretty stable, i'll probably make a proper release in the next few days.

As an aside the last number is the version is the build number, and doesn't need any more dots :P (e.g. it's 1.6.0.122)

Please report if the problem goes away with the latest alpha or doesn't.

**Comment by SargeRyong** [comment] 2015-09-03 05:15
Just reproduced the issue on 1.6.0-122.

Behavior is identical to the previous version.

Forge log contains no mention of "Resource manager" or "Loading language file" anywhere in the log.  

Here's the location of the file, to prove I'm not insane and/or incompetent.
![Localization File Location](http://i.imgur.com/PgFo1pT.png)

And here's the contents of the custombees.cfg file that's in that same directory.
http://pastebin.com/sz0vM7gA

Notably, all the custom bees are created just fine - just the localization on the bees and honeycombs doesn't show up whatsoever.

**Comment by bdew** [comment] 2015-09-03 16:55
That's... odd.

Can you upload your config folder (as zip or rar) somewhere, i'll have a look at it.

Also can you try making an instance with only Gendustry, Forestry and BDLib and see if it still happens. Maybe it's a 3rd party mod doing something odd.

**Comment by SargeRyong** [comment] 2015-09-04 01:32
I trimmed down my mods to just Forestry, Bee mods, and NEI and the bug went away.  It must be another mod interfering.  I'll see if I can try to figure out which one.

**Comment by SargeRyong** [comment] 2015-09-04 03:00
I've found a minimum config that reproduces the bug.

It turns out the 3rd party offender, oddly enough, is CoFH's NetherOres.

Minimum to reproduce is:
Forestry 3.6.3.20
BDLib 1.9.2-104
Gendustry 1.6.0-122
CoFHCore 3.0.3-303 (does not cause bug on it's own, with NetherOre disabled)
NetherOres 2.3.0-12

Here's my configs:  https://drive.google.com/file/d/0B4poLJqzOK85U2w1Rnd2OElheXc/view?usp=sharing

I changed the custombees configuration to remove references to MagicBees in order to rule out an interaction there.

**Comment by SargeRyong** [comment] 2015-09-04 03:52
Can confirm that updating to latest Beta/RC for CoFH (314b1-308) and NetherOres  (2.3.1rc1-19) respectively does not affect the ability to reproduce the issue.

**Comment by skyboy** [comment] 2015-09-04 06:42
You need to load your custom language files into the forge LanguageRegistry, @bdew. The same workaround I have for ensuring it's merged into the vanilla table will fix the problem where it's updated on the next reload instead of updated immediately: https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/mod/BaseMod.java#L265

Despite it being deprecated, it is not going to be removed in 1.7 and ensures data permanence. 1.8+ requires better integration from forge for supporting mods loading user content, regardless of how _the maintainer_ feels about it.

**Comment by bdew** [comment] 2015-09-04 09:02
@SargeRyong, please try [this build](http://jenkins.bdew.net/job/gendustry-1.7.10/123/artifact/build/libs/gendustry-1.6.0.123-mc1.7.10.jar) - the issue should be fixed i hope.

Thanks @skyboy.

> _the maintainer_

:D

**Comment by SargeRyong** [comment] 2015-09-04 10:02
Confirmed,  that fixed it!

**Closed as completed** 2015-09-04 14:19 UTC
