### ISSUE TITLE
Ticking Block entity.

### ISSUE THREAD

**Issue by jbergvall** [bdew-minecraft/gendustry#151] opened 2015-12-22 12:39 UTC
This happens when a queen breeded in the advanced mutatron dies in an industrial apiary. I get thrown out of minecraft with the error message below. I'm using latest gendustry and forestry and I'm not sure if it's gendustry or forestry causing this.

[crash-2015-12-22_13.07.29-server.txt](https://github.com/bdew/gendustry/files/69649/crash-2015-12-22_13.07.29-server.txt)

**Comment by bdew** [comment] 2015-12-23 09:30
That's really weird, the crash is in minecraft code that's responsible for finding the player entity from their profile which is called by forestry when it tries to send an update to a client about known mutations.

I can't reproduce it. Some addional information and testing that might help figure out what's going on: 
- What exact versions of Forestry, Gendustry, BDLib and Forge? 
- How are the bees inserted into the apiary (manualy/automation)? 
- Does it happen with bees bred normally? 
- Does it happen only in industrial apiary or forestry apiaries as well?
- Assuming it's on a dedicated server - Is the server set to online or offline mode? 

Also paging @mezz, maybe they have any idea what's going on here.

I'm storing the player profile in Block.placeBlockAt and if that isn't called for whatever reason, the owner is set to the first player that opens the GUI. Even if that was missed somehow there is a null check in syncToPlayer so it shouldn't cause an error.

**Comment by mezz** [comment] 2015-12-23 09:31
Please update Forestry, it has been fixed in the latest version:
http://minecraft.curseforge.com/projects/forestry/files/2272015

**Comment by bdew** [comment] 2015-12-23 09:47
Interesting, i wonder how would that GameProfile end up with a null username to begin with?

**Comment by jbergvall** [comment] 2015-12-23 12:51
Thanks for the help and quick response! Updating forestry fixed it. 

Thanks for all you hard work!

**Closed as completed** 2015-12-24 07:44 UTC
