### ISSUE TITLE
Small bug texture with DragonAPI ?

### ISSUE THREAD

**Issue by quienti** [bdew-minecraft/gendustry#154] opened 2015-12-31 07:50 UTC
Hi!

After I added DragonAPI with ReactorCraft and RotaryCraft, your bees have a wrong textures

![2015-12-27_11 10 44](https://cloud.githubusercontent.com/assets/7326954/12062274/6dbc5802-af99-11e5-94ec-34abf04198b0.png)

List of all my modpack mods :

`AE2Stuff (0.5.1.9)
Aether2 (1.5.2)
Agricraft (1.4.6-hotfix)
AlternateTerrainGeneration (0.12.0)
AnimationAPI (1.2.4)
AppliedEnergistics2 (Rv3.beta2)
AppleCore (1.1.0)
ArsMagica2 (1.4.0.008)
AsieLib (0.4.2)
bdLib (1.9.4.109)
Bibliocraft (1.11.4)
BiblioWoods[BiomeOPlenty] (1.9)
BiblioWoods[Forestry] (1.7)
BiblioWoods[Highlands] (1.4)
BiblioWoods[Natura] (1.5)
BigReactors (0.4.3A)
BiomesOPlenty (2.1.0.1548)
BloodMagic (1.3.3-17)
Bookshelf (1.0.4.172)
Botania (r1.8-247)
Buildcraft (7.1.14) 
BuildcraftCompat (7.1.3)
Carpenter'sBlocks (3.3.7)
ChickenChunks (1.3.4.19)
Chisel (2.9.4.10)
CodeChickenCore (1.0.7.47)
CoFHCore (3.1.0B1-322)
CompactMachines (1.21)
CTMLib (1.3.0.2)
DecoCraft (2.2.1)
DenseOre (1.6.2)
DragonAPI (10d)
EnchantingPlus (4.0.0.74)
Enchiridon (1.2b)
EnderCore (0.2.0.31_beta)
EnderIO (2.3.0.422_beta)
EnderStorage (1.4.7.37)
EnderZoo (1.0.15.32)
EquivalentExchance3 (0.3.507)
EtFuturum (1.5.2)
ExAstris (1.16-36)
ExNihilo (1.38-49)
ExtraCells (2.3.7b176)
ExtraTiC (1.4.5)
ExtraUtilities (1.2.12)Fastcraft (1.21)
Forestry (4.2.3.51)
GalacticraftCore (3.0.12.404)
GalacticraftPlanets (3.0.12.404)
Gendustry (1.6.4.133)
GildedGamesUtil (1.3.1)
Highlands (2.2.3)iChunUtils (4.2.2)
IguanasTinkerTweak (2.1.5)
InventoryTweaks (1.59-156)
IronChest (6.0.62.742)
JourneyMap (5.1.1)
LunatriusCore (1.1.2.21)
MagicBees (2.4.0)
MagicalCrops (4.0.0Public_Beta5)
MagicalCropsArmoury (4.0.0Public_Beta4)
MagicalCropsDeco (4.0.0Public_Beta4a)
MalisisCore (0.14.0)
MalisisDoors (1.13.0)
Mantle (0.3.2b)
Mariculture (1.2.4.2a)
Mekanism (8.1.7-255)
MekanismGenerators (8.1.7-255)
MekanismTools (8.1.7-255)
Metallurgy (4.0.8.97)
MetallurgyChisel (0.0.11)
MetallurgyCore (4.0.4.18)
MFRCompat-MagicalCrops (1.2.1)
MicdoodleCore (3.0.12.404)
Minechem (5.0.5.406)
MineFactoryReloaded (2.8.1B1-168)
MoreChisels (1.0-28)
Morph (0.9.2)
Natura (2.2.1.a2)
NEIAddons (1.12.15.41)
NEIIntegration (1.1.1)
NetherOres (2.3.1.RC1-19)
NotEnoughItems (1.0.5.118)
NotEnoughKeys (3.0.0b43)
OpenBlocks (1.5)
OpenModsLib (0.9)
Optifine (C1)
Pam'sHarvestCraft (1.7.10Lb)
PortalGun (4.0.0beta6)
ProjectRed (4.7.0.pre9.92)
Railcraft (9.8.0.0)
ReactorCraft (10d)
RedtoneArsenal (1.1.1-89)
Reliquary (1.2.257)
RotaryCraft (10d)
Stackie (1.6.0.36)
Statues (2.1.4)
TConstruct (1.8.8)
Thaumcraft (4.2.3.5)
ThaumicEnergistics (0.9.1.2)
ThaumicExploration (1.1.53) 
ThaumicTinkerer (2.5-510)
ThermalDynamic (1.1.0.161)
ThermalExpansion (4.1.0B1-235)
ThermalFoundation (1.2.1-110)
Waila (1.5.10)
WailaHarvestability (1.1.6) 
WailaPlugins (0.2.0.23)
Wawla (1.3.3)
Ztone (2.2.1)`

**Comment by bdew** [comment] 2015-12-31 08:15
That's odd. The textures are rendered by forestry, i'm just setting different color values for them. I'l try reproducing it when i get the chance and see if i can figure out what's going wrong.

Also paging @ReikaKalseki maybe he has an idea what's going on here.

**Comment by ReikaKalseki** [comment] 2015-12-31 08:59
I have no idea, nor do I see this myself.

**Comment by bdew** [comment] 2015-12-31 12:49
@quienti are you on a Mac by chance?

**Comment by quienti** [comment] 2016-01-01 08:04
@bdew No, sorry, I'm on a Windows 10

**Comment by bdew** [comment] 2016-01-05 15:18
I've looked over the code and i have no idea how or why the textures would be messed up like that. Could possibly be some kind of graphics driver bug.

I also haven't managed to reproduce this with DragonAPI on 3 different systems i have.

**Comment by quienti** [comment] 2016-01-06 07:59
I will ask other player if they have the same problem.
Else, I will search this weekend to remove some mods and maybe found a answer...

**Comment by quienti** [comment] 2016-01-10 11:30
Hummm...
There is juste me who has this bug...
So, too bad
I don't understand why ^^

**Comment by CanisArtorus** [comment] 2016-03-21 04:18
I see now, you're referring to the empty outline with a chisel on it.  I get that too.
DragonAPI/RotaryCraft + Gendustry + Fastcraft isn't enough; but removing Fastcraft from my full pack changed the texture error greatly - to a different error (Queens crownless, princesses hollow with coloured queen crowns, drones hollow).

Restricted list of overlapping mods to OP [#denotes different version]:
AE2Stuff (# 0.4.3.47) AnimationAPI (1.2.4) AppliedEnergistics2 (# rv2-stable-10) AppleCore (# 1.3.0) ArsMagica2 (# 1.4.0.009) bdLib (1.9.4.109) BigReactors (0.4.3A) BloodMagic (1.3.3-17) Botania (# r1.8-249) Buildcraft (# 7.1.15) Carpenter'sBlocks (3.3.7) ChickenChunks (1.3.4.19) Chisel (# 2.5.1.44) CodeChickenCore (1.0.7.47) CoFHCore (# 3.1.2-325) CompactMachines (1.21) DenseOre (1.6.2) DragonAPI (# 11b) EnchantingPlus (# 3.0.2-d) EnderCore (0.2.0.31_beta) EnderIO (# 2.2.8.381) EnderStorage (1.4.7.37) ExtraCells (# 2.3.9b188) ExtraTiC (1.4.5) ExtraUtilities (1.2.12) Fastcraft (1.21) Forestry (# 4.2.10.58) Gendustry (# 1.6.3.132) iChunUtils (4.2.2) IguanasTinkerTweak (2.1.5) InventoryTweaks (# 1.59-dev-152) IronChest (# 6.0.62.741) JourneyMap (# 5.1.4-unlimited) LunatriusCore (1.1.2.21) MagicBees (# 2.4.3) MalisisCore (# 0.14.3) MalisisDoors (# 1.13.2) Mantle (0.3.2b) Mekanism (# 8.1.9-265) MekanismGenerators (# 8.1.9-265) MekanismTools (# 8.1.9-265) MineFactoryReloaded (# 2.8.1-174) Natura (# 2.2.0.1) NEIAddons (# 1.12.14.40) NEIIntegration (# 1.1.2) NotEnoughItems (1.0.5.118) OpenBlocks (# 1.5.1) OpenModsLib (# 0.9.1) Pam'sHarvestCraft (1.7.10Lb) PortalGun (4.0.0-beta-6) ProjectRed (# 4.7.0.pre12.95) Railcraft (# 9.9.0.0) ReactorCraft (# 11b) RotaryCraft (# 11b) TConstruct (1.8.8) Thaumcraft (4.2.3.5) ThaumicEnergistics (# 0.8.10.10) ThaumicExploration (1.1-53) ThaumicTinkerer (# 2.5-1.7.10-164) ThermalDynamic (1.1.0.161) ThermalExpansion (# 4.1.2-240) ThermalFoundation (# 1.2.3-112) Waila (1.5.10) WailaPlugins (0.2.0.23) Wawla (1.3.3).

**Comment by bdew** [comment] 2016-03-21 09:41
It's a long shot, but... can you guys try disabling the forge splash screen (enabled=false in splash.properties). It seems to fix a similar but more widespread texture corruption issues on macs, maybe it can also help here?

I still have absolutely no idea what causes this, and no luck reproducing it.

**Comment by CanisArtorus** [comment] 2016-03-21 18:04
splash:enabled=false was pre-existing, using Better loading screen to replace - re-enabling had no effect.
Also a Win 10, java8 system.

Only gendustry bees -> BdLib, CoFh Core, Forestry, Gendustry
Required to duplicate: ALL of: DragonAPI, Thermal Foundation, & MalisisDoors -> MalisisCore
Changes radically: Fastcraft, Thaumcraft

Removing MalisDoors Sometimes fixes it.  
Removing Fastcraft never fixes it, but always changes the type of problem to class cycling (larvae with princess hats, hollow princesses with queen hats, blobby queens, hollow drones).
![2016-03-21_11 56 57](https://cloud.githubusercontent.com/assets/17414970/13928660/40ea9336-ef5c-11e5-8b09-ff1bd33315ce.png)

Removing Thaumcraft changed it from an item overlay to an abstract arch in bee color.
![2016-03-21_11 55 01](https://cloud.githubusercontent.com/assets/17414970/13928643/30b34710-ef5c-11e5-89cd-2c4d23334b74.png)

Removing Either DragonAPI or Thermal Foundation Always fixes it.

Hope that helps.

**Comment by OneEyeMaker** [comment] 2016-09-01 13:40
@bdew 
I have the same issue with GenDustry. It occurs if GenDustry + DragonAPI + ThermalFoundation are installed. 
I spent some time to search, what causes this render bug. And I found it: ThermalFoundation _replaces **static** icon of blaze powder (vanilla item) with **animated** one_. And this mod does it ... dirty... 
Just disabling animated icon of blaze powder in `config/cofh/thermalfoundation/client.cfg` resolves this problem at all.

**Comment by ReikaKalseki** [comment] 2016-09-01 14:20
Can someone else test this? If at least one other person can confirm, time to ping someone from CoFH.

**Comment by bdew** [comment] 2016-09-01 15:23
I never managed to find a way to reproduce this, so i can't test myself.

Sounds really weird. I'll guess i'll take a look at what CoFH is doing with that texture when i get the chance.

Added: And honestly since 1.7.10 is pretty much done and the whole item rendering system was replaced in newer versions - it's probably not something that will be relevant in the future anyway.

**Comment by bdew** [comment] 2017-10-12 16:45
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:45 UTC
