### ISSUE TITLE
Null Pointer error in 1.6.4.6 for MC 1.10.2

### ISSUE THREAD

**Issue by Gunner76th** [bdew-minecraft/gendustry#170] opened 2016-07-07 23:36 UTC
This is a forward from our internal crash reporting repo. If you need any information in addition to what is supplied please let me know. 

The server is running Linux Ubuntu with Java 8 update 91 and forge 12.18.0.2007
The modpack in use is All The Mods, which is hosted on the Curse platform. 

I was informed by the player, that he was in the vicinity of a beehive with a bucket in his hotbar (it was the active item as well). Once he discarded (dropped on the ground) his bucket, his client stopped crashing. 

**_Begin internal issue report**_
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods):
AllTheMods 1.10 v0.6

Steps to reproduce the issue or crash:
Tried to log in 3 more times, still wouldnt let me

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com):
http://pastebin.com/tUcp3fzC

OS of Client computer:
Windows 10

Version of JAVA on Client:
1.8.0_25

Version of Minecraft:
10.2

Version of Forge:
12.18.0.2007

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):
Allthemods, Spice of life and roguelikedungeons disabled
**_End internal issue report**_

https://github.com/IHOC/Server/issues/3

**Comment by bdew** [comment] 2016-07-08 05:42
Duplicate of #169, was fixed in 1.6.4.7

**Closed as completed by bdew** 2016-07-08 05:42 UTC
