### ISSUE TITLE
SMP Console spam:

### ISSUE THREAD

**Issue by jalapeno777** [bdew-minecraft/gendustry#6] opened 2014-01-09 16:27 UTC
Since my members started using gendustry machines we started getting a ton of console spam.

Ex.
2014-01-09 04:31:58 [WARNING] [IC2] EnergyNet.removeTileEntity: net.bdew.gendustry.machines.mproducer.TileMutagenProducer@799fe36d (net.bdew.gendustry.machines.mproducer.TileMutagenProducer@799fe36d) wasn't found (added), skipping

This happens across all machines but primarily apiaries.

There's easily about 45/second messages like this that occur.  Is there any way to identify which apiaries are causing this?

If it's not possible...would it be plausible to have a configuration item to disable the allowance of using IC2 on gendustry machines?  That would then eliminate this spam occurring as it would force my users to use a non IC2 method.

**Comment by jalapeno777** [comment] 2014-01-09 17:17
After some further investigation it looks some some machines from time to time start having this bug and they won't accept any form of energy input.  Breaking the power supply cable or the machine does not resolve the problem...placing them back in the same spot bring back an error saying that block is already part of the energy network.

While they will not draw power, gendustry machines down the cable line from them will work perfectly fine.

I'm not sure what other information I can supply...if you have anything specific you need please let me know and I will do my best to accomodate.

**Comment by bdew** [comment] 2014-01-09 18:57
Please try [this](http://jenkins.bdew.net/job/gendustry/lastSuccessfulBuild/artifact/build/libs/gendustry-mc164-0.9.10.35.jar) version, i think it should fix the issue you are having though i couldn't reproduce it here. I also added options to disable IC2 (and other energy networks) as a workaround in case it doesn't.

Also in case it doesn't work, can you be more specific about your setup? What version of IC2 are you using? Are the machines having issues being chunk loaded? Is this a normal server or MCPC+?

**Comment by bdew** [comment] 2014-01-14 01:30
I think the version above had a bug in it's config handling, don't use it. The fixes are in 1.0.0 that i released today.

**Comment by bdew** [comment] 2014-01-16 08:10
As i've not heard again from the original reporter i'm assuming it's indeed fixed so i'll close this. If there are still issues - comment here and i'll reopen it.

**Closed as completed by bdew** 2014-01-16 08:10 UTC
Labels: bug
