### ISSUE TITLE
EnergyNet.addTileEntity 

### ISSUE THREAD

**Issue by Dream-Master** [bdew-minecraft/gendustry#117] opened 2015-07-31 11:45 UTC
I found this in the Sever log.

EnergyNet.addTileEntity: net.bdew.gendustry.machines.apiary.TileApiary@48a89ab2 (net.bdew.gendustry.machines.apiary.TileApiary@48a89ab2) is still conflicting with net.bdew.gendustry.machines.apiary.TileApiary@5c00782 using the same position (overlapping), aborting

I guess it could be the GT Cables converting now EU to RF (GT unofficial version from Blood Asp 5.08.25.)

**Comment by bdew** [comment] 2015-07-31 18:04
Does it happen with normal IC2 cables? (all machines in gendustry can work with IC2 power)

**Comment by Dream-Master** [comment] 2015-07-31 18:34
We disabled IC2 cables because they are lossless(balance breaking) so I not tested it with ic2 cables yet.
Should I?

**Comment by bdew** [comment] 2015-08-01 09:37
I've tried with latest gendustry, ic2 exp and that Blood Asp version of GT5, with the option to disable IC2 cables and couldn't reproduce the issue.

Is this happening to all apiaries on your server or just some? Anything special going on around them?

**Comment by Dream-Master** [comment] 2015-08-01 09:54
I am not sure i get this error on start up the Server. Is it a serious issue or just a warning?

```
Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.apiary.TileApiary@3ff49949 (net.bdew.gendustry.machines.apiary.TileApiary@3ff49949) is still conflicting with net.bdew.gendustry.machines.apiary.TileApiary@3563ad4b using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.imprinter.TileImprinter@727ddec (net.bdew.gendustry.machines.imprinter.TileImprinter@727ddec) is still conflicting with net.bdew.gendustry.machines.imprinter.TileImprinter@9818345 using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.replicator.TileReplicator@65892b06 (net.bdew.gendustry.machines.replicator.TileReplicator@65892b06) is still conflicting with net.bdew.gendustry.machines.replicator.TileReplicator@568700dc using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.mutatron.TileMutatron@1c0718a8 (net.bdew.gendustry.machines.mutatron.TileMutatron@1c0718a8) is still conflicting with net.bdew.gendustry.machines.mutatron.TileMutatron@2cdad01 using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.transposer.TileTransposer@622863e7 (net.bdew.gendustry.machines.transposer.TileTransposer@622863e7) is still conflicting with net.bdew.gendustry.machines.transposer.TileTransposer@3c6a2c4 using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.extractor.TileExtractor@76097032 (net.bdew.gendustry.machines.extractor.TileExtractor@76097032) is still conflicting with net.bdew.gendustry.machines.extractor.TileExtractor@665fde8 using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.sampler.TileSampler@105b23ac (net.bdew.gendustry.machines.sampler.TileSampler@105b23ac) is still conflicting with net.bdew.gendustry.machines.sampler.TileSampler@3343d422 using the same position (overlapping), aborting
[10:45:06] [Server thread/WARN]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.liquifier.TileLiquifier@4761d534 (net.bdew.gendustry.machines.liquifier.TileLiquifier@4761d534) is still conflicting with net.bdew.gendustry.machines.liquifier.TileLiquifier@669f7340 using the same position (overlapping), aborting
```

I will ask my player for more infos. Thanks for you help so far.

**Comment by bdew** [comment] 2015-08-01 16:52
How serious it is depends on what's really causing it. If the machines are still receiving power and working correctly then it's probably not  too bad.

**Comment by Dream-Master** [comment] 2015-08-01 17:20
I think they working normally.

**Comment by bdew** [comment] 2015-08-12 06:48
Since i can't reproduce the issue and it doesn't seem to cause actual gameplay problems i'll assume it's either a quirk in the energy net or some other mod doing something weird and close the issue.

If you have any new insight comment here and i'll reopen the issue.

**Closed as completed by bdew** 2015-08-12 06:48 UTC
