### ISSUE TITLE
advanced mutatron Soft-locking with custom bees

### ISSUE THREAD

**Issue by Quaxitos** [bdew-minecraft/gendustry#217] opened 2017-03-11 20:41 UTC
When creating new custom bees for things like BoP gems, TE5 metals and pyrotheum, the game will soft lock if i use the Advanced Mutatron to breed them. I can pull them from JEI just fine, use them for production just fine, but attempting to get them via breeding, clicking in the lower portion of the GUI causes a 7 minute+ soft lock.

**Comment by bdew** [comment] 2017-03-13 08:55
I can't reproduce this issue. Please post the exact versions of all involved mods, your logs and the config files you are using.

**Comment by bdew** [comment] 2017-10-12 16:53
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:53 UTC
