### ISSUE TITLE
Custom drops don't follow custom squeezer recipe

### ISSUE THREAD

**Issue by Stalkstalks** [bdew-minecraft/gendustry#134] opened 2015-09-05 23:39 UTC
I define some custom drops with custom squeezer recipes. NEI shows that the squeezer will produce what the custom recipe tells it to. However, when I actually run the drops through the squeezer, they produce 100mb of honey and sometimes propolis.

I'm using the same config I posted for https://github.com/bdew/gendustry/issues/133, and using the build you linked to for that as well.

**Comment by bdew** [comment] 2015-09-06 18:26
After some investigation the problem is that forestry started using oredictionary for squeezer recipes at some point. Since all honeydrops are registered into OreDictionary it picks up the "standard" honeydrop recipe instead of the custom one.

I've talked with people in #forestry-dev about it and getting a reasonable fix for it in 3.6 is probably not going to happen since 4.0 should be coming out in the next few weeks.

I'll make a PR to forestry to prioritize specific recipes over oredict that should fix this for 4.0.

In the meanwhile you could disable oredict registration by [removing this line](https://github.com/bdew/gendustry/blob/mc1710/resources/assets/gendustry/config/recipes.cfg#L239) and either shipping a jar with modified config or putting it in overrides folder. This might or might not break something else, i haven't tested it. Or just wait for Forestry 4.0 to come out.

**Comment by Stalkstalks** [comment] 2015-09-06 19:25
Dang. If i try to remove the gendustry honey drop ore dictionary entry using say
   dropHoney.remove(gendustry:HoneyDrop);
in minetweaker, would you expect it to break anything important in gendustry?

**Comment by bdew** [comment] 2015-09-06 19:36
I don't think it will break anything in gendustry itself, but if anything else uses that OD entry for recipes they obviously won't work.

**Comment by bdew** [comment] 2015-09-06 19:45
Here's the proposed fix in forestry - ForestryMC/ForestryMC#815

**Comment by bdew** [comment] 2015-09-10 07:47
Should be fixed in Forestry 3.6.5 stable and 4.0.0 alpha builds

**Closed as completed by bdew** 2015-09-10 07:47 UTC
