### ISSUE TITLE
Gendestury causing crashes on loading (again?)

### ISSUE THREAD

**Issue by Yamza** [bdew-minecraft/gendustry#277] opened 2018-08-16 15:06 UTC
Currently running ATM3 (6.0 PTR) [gendustry-1.6.5.8-mc1.12.2] using MultiMC: https://pastebin.com/T0zwnpLR

Other people are also reporting issues on ATM3 5.9.8D (current release version)
https://pastebin.com/65PzuzQk
https://pastebin.com/Tzg2cwnb
https://pastebin.com/h81XEYqG

First report was -1:07 from the time of this post.

People using Twitch have said that changing to jar launcher running current Java (_181) has "fixed" the issue. Not sure of a solution for MultiMC.

**Comment by davqvist** [comment] 2018-08-16 15:10
Someone has the same issue in my Exoria modpack. Any ideas?
https://pastebin.com/WuSvHDw5

**Comment by TheSeldomSeenKid** [comment] 2018-08-16 15:11
Validated on Exoria. Failure after Microsoft Update on 8/15/2018.

**Comment by BakerTS** [comment] 2018-08-16 15:12
Same issue with All The Mods 3 - 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GenDustry (gendustry)

**Comment by TheSeldomSeenKid** [comment] 2018-08-16 15:13
It seems to be related to the Microsoft update.

**Comment by Sharkske** [comment] 2018-08-16 15:14
how df did a Microsoft update somehow break mc

**Comment by Discomanco** [comment] 2018-08-16 15:15
I got the newest update of W10 as well, but doesn't seem to be affected from the crashes in either of our packs... at least not yet

**Comment by Sharkske** [comment] 2018-08-16 15:16
try updating and restarting ur computer than let me know :)

**Comment by Discomanco** [comment] 2018-08-16 15:17
I did that last night (some 18 hours ago). A lot of our users are reporting of the same issues, with multiple packs (ours included).
Just not me ._.

**Comment by BakerTS** [comment] 2018-08-16 15:18
Can confirm: not just gendustry issue, load MC with gendustry disabled and you get the same error from another mod

**Comment by Discomanco** [comment] 2018-08-16 15:19
Guess it just shows Gendustry because it's the first affected mod being loaded

**Comment by Sharkske** [comment] 2018-08-16 15:19
same alot of our users are reporting the same issue, plus myself i found that editing settings in twitch helped i changed it to this and i can open modpacks without an issue https://i.imgur.com/muwOE9i.png

**Comment by Sharkske** [comment] 2018-08-16 15:20
it looks like the ver of java twitch uses by default maybe the issue and needs to be updated, that or the new launcher is an issue idk still playing with it

**Comment by Yamza** [comment] 2018-08-16 15:21
I was able to load the pack, with gendustry, prior to the time I referenced in my post.

**Comment by Discomanco** [comment] 2018-08-16 15:21
One of our users reporting an issue is already on Jar version (Java 181), so it may help for some, but not all

**Comment by TheSeldomSeenKid** [comment] 2018-08-16 15:21
Have no idea. Exoria worked yesterday (launch via twitch). Performed a Microsoft update and reboot. Now failure on launch with error tied to Gendustry, For Exoria turn off Gendustry via twitch launcher. It works. So it may be multiple mods affected but not all mods. Note: Updated FoamFix on exoria as it was showing up as an error.

**Comment by Discomanco** [comment] 2018-08-16 15:22
We have also gotten errors from Extra Utilities 2, after some tried to disable Gendustry

**Comment by Sharkske** [comment] 2018-08-16 15:24
PANIC!!!!!!!!

**Comment by Sharkske** [comment] 2018-08-16 15:26
its an issue with 1.12 modpacks i notice 1.10 and 1.7 is fine

**Comment by purehyper** [comment] 2018-08-16 15:33
Yeah FTB Revelations is down... Maybe try to start offline?

**Comment by Yamza** [comment] 2018-08-16 15:38
Seems to be more than Gendustry, https://github.com/rwtema/Extra-Utilities-2-Source/issues/159

**Comment by shadoxxhd** [comment] 2018-08-16 15:38
#271

**Comment by Kittysnape** [comment] 2018-08-16 15:41
What Sharkske said about changing the launcher fixed it for me.

**Comment by Sharkske** [comment] 2018-08-16 15:41
it has nothing to do with any of the mods becuz there hasnt been any changes with them it is something core based, like in java or windows like at the top of this issue mine did start after the windows update

**Comment by TheSeldomSeenKid** [comment] 2018-08-16 15:42
The gendustry and extrautilities are common at: com.google.common.eventbus.Subscriber
“When in danger or in doubt, run in circles, scream and shout.” - Herman Wouk

**Comment by lylehenderson** [comment] 2018-08-16 15:43
Just thought I'd point out that it can't be Microsoft related since I'm on Linux, have not performed any updates of any kind.  The only thing I've done is launch FTB, which loadloads all the packs... etc.

**Comment by purehyper** [comment] 2018-08-16 15:43
I don't believe it was the windows update... Someone who plays on a FTB Revelations server is on windows 8 with no update

**Comment by purehyper** [comment] 2018-08-16 15:44
Thank you Lyle

**Comment by shadoxxhd** [comment] 2018-08-16 15:44
I'm working on a dirty class edit fix right now

**Comment by SAFCxHarter** [comment] 2018-08-16 15:44
I have a temporary fix until Windows sort their stuff out, if you are using the Twitch Launcher this should work

Step 1: File>Settings
Step 2: Minecraft Tab
Step 3: Scroll down to "Launch Method"
Step 4: Switch from "Native Launcher" to "Jar Launcher"
Step 5: Select the latest version of Java you have installed
Step 6: Log back into Minecraft with the old launcher
Step 7: Close the launcher because it will try to launch Vanilla 1.13
Step 8: Launch the modpack you were playing originally, it should all work now

Hopefully this works for everyone besides me

**Comment by shadoxxhd** [comment] 2018-08-16 15:45
The problem is a language file update.

**Comment by purehyper** [comment] 2018-08-16 15:45
It may be dependant on files that are temporarily downloaded on start up and that may have been corrupted on the mod devs side

**Comment by shadoxxhd** [comment] 2018-08-16 15:47
https://drive.google.com/file/d/1SdXFFSYyCCNhV7EUSr3XvNwlOqwjImss/view?usp=sharing
Put this in your gendustry.jar in the net/bdew/gendustry/misc/ folder and overwrite.
I removed the language code check - this might result in breaking other languages than en_us, but might let you play.
Required gendustry version: 1.5.4.8.
Interestingly, while it fixed the gendustry crash for me, extrautils seems to have problems, too.

**Comment by ghost** [comment] 2018-08-16 15:55
Seems to have done the trick. Tyvm.

**Comment by MustardTig3r** [comment] 2018-08-16 15:56
Great thanks, that worked for me too.

**Comment by shadoxxhd** [comment] 2018-08-16 15:56
Extrautils still crashes the game for me, so my work isn't done yet.

**Comment by MTCoster** [comment] 2018-08-16 15:57
@shadoxxhd Any mod that reads the .lang metadata without a NP check will need a patch

**Comment by purehyper** [comment] 2018-08-16 15:59
Anyone have any idea of why this has happened?

**Comment by Kollamma** [comment] 2018-08-16 16:03
Sorry noob question - how do i use that .class file to fix this?

**Comment by MTCoster** [comment] 2018-08-16 16:04
@purehyper There was an asset update right before this swathe of crashes, presumably the .lang files were updated in a way that several mods weren't expecting

**Comment by purehyper** [comment] 2018-08-16 16:06
@MTCoster Ah cheers... well that's annoying I suppose its gonna be a while then till the devs make their mods compatible

**Comment by MustardTig3r** [comment] 2018-08-16 16:07
Open the gendustry-1.6.5.8-mc1.12.2.jar file with 7Zip.  You can then overwrite the class file inside the jar.  Take a copy just in case :)

**Comment by ghost** [comment] 2018-08-16 16:07
For those less savvy here's the fixed version.

https://drive.google.com/file/d/1T74nJwE00hKbwbOEsZU_7A0Y9DwQ_ZlP/view?usp=sharing

Alternatively, change the .jar to .zip, open it, find the location as in the instructions and replace the file.

**Comment by Shybella** [comment] 2018-08-16 16:08
This isn't practical for everyone. FTB will need to push an update. 75% of people (and im being liberal) cannot even find their modpack directory.

let alone swap a class file.

**Comment by ulobaka** [comment] 2018-08-16 16:08
Need EU2 fix gogogo @shadoxxhd

**Comment by not-na** [comment] 2018-08-16 16:08
I also seem to have the same crash on Linux/Ubuntu 18.04 using MultiMC. This seems to suggest that Windows is not at fault.
Log: https://paste.ee/p/dmXO6

**Comment by shadoxxhd** [comment] 2018-08-16 16:10
https://drive.google.com/drive/folders/1iLvRGb9leb9SZ8CR_r0KYPjhHFEQnFjR?usp=sharing this will contain any fix I put together

**Comment by Kollamma** [comment] 2018-08-16 16:10
Haha yeah, just EU2 to fix and we back in business! Thanks MustardTiger for the instructions - got my Gendustry working at least!

**Comment by onefusion** [comment] 2018-08-16 16:11
@shadoxxhd just wanted to give you some appreciation for your work on helping others fix this. keep up the good work.

**Comment by DacodaDragon** [comment] 2018-08-16 16:11
@shadoxxhd You're doing super well, thank you in advance!

**Comment by DaRealMcCloud** [comment] 2018-08-16 16:14
@SAFCxHarter your instructions worked for me.

**Comment by shadoxxhd** [comment] 2018-08-16 16:17
trying out a possible fix right now... fixing EU2 is definitely much harder than gendustry, since the crash is kinda strange

**Comment by MTCoster** [comment] 2018-08-16 16:18
So I found the problem... In the latest asset manifest there's a typo: `en_us.lang` has been replaced with `en_ud.lang`.  Therefore no .lang file is being loaded for the default `en_us` language, thus the NP errors causing all these crashes!

**Edit:** It turns out `en_ud.lang` is an intentional separate language.  The real issue here is that `en_us.lang` doesn't exist in the manifest at all.

**Comment by Kollamma** [comment] 2018-08-16 16:18
we beleive in you!

**Comment by ulobaka** [comment] 2018-08-16 16:20
@MTCoster and how it help us???

**Comment by shadoxxhd** [comment] 2018-08-16 16:22
someone could host the correct manifest and we edit our hosts file to redirect to his server? this would be extremely noob-unfriendly and may have side effects though

**Comment by Kollamma** [comment] 2018-08-16 16:23
hopefully someone notices the typo shortly and fixes it =)

**Comment by shadoxxhd** [comment] 2018-08-16 16:23
IT LOADS

**Comment by shadoxxhd** [comment] 2018-08-16 16:24
fixed jar is uploaded.

**Comment by ninetaled** [comment] 2018-08-16 16:26
Where do i put file in extrautils2-1.12-1.7.6.jar?

**Comment by DacodaDragon** [comment] 2018-08-16 16:26
Is it possible that you can upload the seperate class files as well? I have a slightly older version of EU2. I am not sure if it breaks stuff

**Comment by Hypocrita20XX** [comment] 2018-08-16 16:26
@shadoxxhd You're doing an awesome job! I really appreciate it and I'm sure others do as well. =-)

**Comment by shadoxxhd** [comment] 2018-08-16 16:26
to sum it up: copy the 2 jar files from https://drive.google.com/drive/folders/1iLvRGb9leb9SZ8CR_r0KYPjhHFEQnFjR?usp=sharing
to your mods folder

**Comment by shadoxxhd** [comment] 2018-08-16 16:26
@JaronKuijper sure

**Comment by ninetaled** [comment] 2018-08-16 16:28
oh its the full jar this time not just the one file. Thx for all the help!

**Comment by FloxyTek** [comment] 2018-08-16 16:28
i think most modpacks- if not update use extrautils version 1.8.1 at least ftb revelation 2.3 does a fix for this version would be awesome

**Comment by shadoxxhd** [comment] 2018-08-16 16:30
class files are only for those who know what they are doing! supported versions are eu2: 1.8.2 and gendustry: 1.6.5.8. other versions might or might not work (untested).
where to put them: the extrautils 2 one into com/rwtema/extrautils2/; the gendustry one into net/bdew/gendustry/misc/

**Comment by ulobaka** [comment] 2018-08-16 16:31
@shadoxxhd thanks u bro!!

**Comment by Sharkske** [comment] 2018-08-16 16:32
no offense to anyone here, im  happy to see everyone trying to help everyone get into da best game in the world, but there really should be a more professional fix done by either the people that caused this or all of the mod devs along with the modpack creators

**Comment by tterrag1098** [comment] 2018-08-16 16:33
@Sharkske This is caused by a change *Mojang* made to the assets. I'm talking to a Mojang dev atm about it, it seems like they are aware it's caused an issue.

**Comment by shadoxxhd** [comment] 2018-08-16 16:33
sure, but since I don't have a proper build environment set up this was the only thing I could do.

**Comment by purehyper** [comment] 2018-08-16 16:35
@shadoxxhd well done mate, but I agree with @Sharkske its down to the devs and this shouldn't of happened, this is why game testing is a thing and they should have realised the typo in the .lang file before pushing it into the public

**Comment by Sharkske** [comment] 2018-08-16 16:35
Yea its just hard to get simple minded users to know how to download a jar and put it into there modpack folders, this is coming from a moded MC network owner

**Comment by Hypocrita20XX** [comment] 2018-08-16 16:35
A proper fix is nice, but that will take time. In the meantime, what Shadow has done is just fine. Also I can confirm that the fixed jars are working as intended. Thanks again @shadoxxhd !

**Comment by tterrag1098** [comment] 2018-08-16 16:36
Peterix has provided a simpler hotfix if you can't wait for a Mojang fix:

![](https://cdn.discordapp.com/attachments/254806806516203520/479689083761721386/unknown.png)

**Comment by Sharkske** [comment] 2018-08-16 16:36
yea i agree it works

**Comment by zloebl777** [comment] 2018-08-16 16:36
@shadoxxhd I just tested the .class file with ExU2 1.8.3.  The game loads and seems fine, but I didn't do any functionality testing.

**Comment by shadoxxhd** [comment] 2018-08-16 16:38
@zloebl777 looking at the eu2 changelog, it shouldn't cause any issues it doesn't cause on 1.8.2.

**Comment by DacodaDragon** [comment] 2018-08-16 16:39
Eu2 1.8.1 for revelations 2.3.0 seems good as well. Thank you for the fix.

**Comment by shadoxxhd** [comment] 2018-08-16 16:40
1.8.1 fix jar is online btw.

**Comment by Shybella** [comment] 2018-08-16 16:41
This is a quick video if using Twitch to play Direwolf20 1.12.2 again
https://youtu.be/aBhm_4f3Oi8

**Comment by shadoxxhd** [comment] 2018-08-16 16:45
@Shybella can you put my link in the description for people using ftblauncher or similar?

**Comment by lylehenderson** [comment] 2018-08-16 16:50
Sorry wrong thread.. moving.

**Comment by shadoxxhd** [comment] 2018-08-16 16:55
Try disabling google analytics.

**Comment by FloxyTek** [comment] 2018-08-16 16:58
@shadoxxhd fixes worked ty for your help

**Comment by Realta23** [comment] 2018-08-16 17:12
I made an account on github just to say: Thank you! @shadoxxhd

**Comment by Yamza** [comment] 2018-08-16 17:15
Thank you for your quick work on these hot fixes @shadoxxhd.

**Comment by Iomega0318** [comment] 2018-08-16 17:24
@shadoxxhd We are still running on Rev 2.2.0, can you possibly put up a fix for **extrautils2-1.12-1.7.6.jar**?

Please and thank you, so far your other fixes have worked great!

**Comment by shadoxxhd** [comment] 2018-08-16 17:40
@Iomega0318 uploaded.

**Comment by Finnyfinnfinn23** [comment] 2018-08-16 17:41
thanks shodoxxhd I was about to ask for that
:)

**Comment by billykitty** [comment] 2018-08-16 17:43
thanks to all

**Comment by Iomega0318** [comment] 2018-08-16 18:02
Thank you! It has worked wonderfully!

**Comment by morguldir** [comment] 2018-08-16 19:06
@tterrag1098 

```json
    "assetIndex": {
        "id": "1.12",
        "sha1": "e75e9535754c6f2158b0b18b35660f45c4495d78",
        "size": 169257,
        "url": "https://launchermeta.mojang.com/mc/assets/1.12/e75e9535754c6f2158b0b18b35660f45c4495d78/1.12.json",
        "totalSize": 127722338
    },
```

**Comment by morguldir** [comment] 2018-08-16 19:21
@tterrag1098 at least post the text :D

```json
    "assetIndex": {
        "id": "1.12",
        "sha1": "e75e9535754c6f2158b0b18b35660f45c4495d78",
        "size": 169257,
        "url": "https://launchermeta.mojang.com/mc/assets/1.12/e75e9535754c6f2158b0b18b35660f45c4495d78/1.12.json",
        "totalSize": 127722338
    },
```

The file is in versions/1.12.2/1.12.2.json in my ftb and minecraft folder, i had to make the file read-only as well.

**Comment by purehyper** [comment] 2018-08-16 19:46
I get a File Hash error when I changed the 1.12.2 file … Was to be expected I suppose

**Comment by rylm** [comment] 2018-08-16 19:49
Same here, I get the hash mismatch error

**Comment by purehyper** [comment] 2018-08-16 19:51
I suppose its a security feature for mojangs servers to only allow their latest release of their indexes to be released by mc checking the hash before downloading and if theres a mismatch to reconstruct the 1.12.2 file... rather complicated and impressive when it comes down to it

**Comment by purehyper** [comment] 2018-08-16 19:54
its probably because that's only for 1.12 …
https://launchermeta.mojang.com/mc/assets/1.12/e75e9535754c6f2158b0b18b35660f45c4495d78/1.12.json
open it in your browser the file is for 1.12

**Comment by purehyper** [comment] 2018-08-16 19:57
Oh hold on theres a 1.12 file in install > Assets > 1.12.json full of hash codes

**Comment by purehyper** [comment] 2018-08-16 19:58
Assets>indexes

**Comment by rylm** [comment] 2018-08-16 20:07
How did you all manage to get it to work? No matter what I do the launcher give me this error about hashes.

**Comment by shadoxxhd** [comment] 2018-08-16 20:16
@rylm The easiest thing is probably still my jar fix: https://youtu.be/HYN9GwFWkp4

**Comment by Shybella** [comment] 2018-08-16 21:08
This should be resolved now. If you still have the problem reinstall your pack.

**Comment by TheSeldomSeenKid** [comment] 2018-08-16 21:29
Validated works now in Exoria with Twitch. No changes to launcher or changes to jars. Thanks.

**Closed as completed** 2018-08-20 18:18 UTC
